### ISSUE TITLE
Phone reboot automatically 

### ISSUE THREAD

**Issue by Mohitgurjar007** [PixelPlusUI-Devices/official_devices#121]
I have install pixel plus ui 4.5 in my poco x3 pro , the rom is overall smooth experience but i have some serious issues .
1. Phone hang (screen freedge ) and automatically restart .
2. The charging speed is slow , charging increased by more then 40 % 
3. Heating temperature increases in a short time of use and goes to 47°c.

**Comment by ugly-kid-af** [comment]
Install latest update

**Comment by Mohitgurjar007** [comment]
there is no update showing

**Comment by ugly-kid-af** [comment]
https://ppui.site/download

**Comment by Mohitgurjar007** [comment]
Is 4.6 2nd uodate  is the latest update ,, i am asking is because it show latest version 4.7 on on page in which we select phone model and shows 4.6 in the download page

**Comment by Mohitgurjar007** [comment]
Is 4.6 2nd update is the latest update ,, i am asking is because it show
latest version 4.7 on on page in which we select phone model and shows 4.6
in the download page.
